# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TVShowApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TVShowApp
  pod 'Moya'
  pod 'Kingfisher'

end
