source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'
inhibit_all_warnings!


target 'TVShowApp' do
  use_frameworks!
  pod 'Moya', '~> 15.0.0'
  pod 'Kingfisher', '~> 7.3.2'
  pod 'SwiftGen', '~> 6.6.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
   end
  end
 end