#==================================================================================================
# Xcodegen documentation
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-scheme
#==================================================================================================

# Definimos o nome do projeto
name: TVShowApp

# Configuracoes de compilacao
settings:
  MARKETING_VERSION: "1.0.0"
  SWIFT_VERSION: 5.0
  VERSIONING_SYSTEM: "apple-generic"
  CODE_SIGN_IDENTITY: "iPhone Developer"
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
  ARCHS: $(ARCHS_STANDARD)
  
options:
  bundleIdPrefix: com.giulianoaccorsi
  xcodeVersion: 13.4.1
  deploymentTarget:
    iOS: 15.0

targets:
  TVShowApp:
    type: application
    platform: iOS
    sources:
      - TVShowApp
    preBuildScripts:
      - script: |
                if [[ -f "${PODS_ROOT}/SwiftGen/bin/swiftgen" ]]; then
                  "${PODS_ROOT}/SwiftGen/bin/swiftgen"
                else
                  echo "warning: SwiftGen is not installed. Run 'pod install --repo-update' to install it."
                fi
        name: SwiftGen
    postCompileScripts:
    - script: |
              export PATH="$PATH:/opt/homebrew/bin"
              if which swiftlint > /dev/null; then
                swiftlint
              else
                echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
              fi
      name: Swiftlint
    scheme:
      testTargets:
      - name: TVShowAppTests
        randomExecutionOrder: true
      gatherCoverageData: true
      coverageTargets:
        - TVShowApp
    settings:
      configs:
        Debug:
          ONLY_ACTIVE_ARCH: YES
    info:
      path: TVShowApp/Info.plist
      properties:
        UISupportedInterfaceOrientations: []
        NSAppTransportSecurity: true
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate

  TVShowAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TVShowAppTests
        includes:
          - "**/*.swift"

    settings:
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/TVShowApp.app/TVShowApp"

    info:
      path: TVShowAppTests/Info.plist