#==================================================================================================
# Xcodegen documentation
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-scheme
#==================================================================================================

# Definimos o nome do projeto
name: TVShowApp

# Configuracoes de compilacao
settings: 
  MARKETING_VERSION: "1.0.0"
  SWIFT_VERSION: 5.0
  VERSIONING_SYSTEM: "apple-generic"
  CODE_SIGN_IDENTITY: "iPhone Developer"
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
  ARCHS: $(ARCHS_STANDARD)

options:
  bundleIdPrefix: com.giulianoaccorsi
  xcodeVersion: "13.4.1" # Versao de compilacao do nosso app
  deploymentTarget:
    iOS: "15.0" # Base target do nosso app

# definicao do target do projeto e testes
targets: 
  TVShowApp:
    platform: iOS
    type: application

    sources:
      - path: TVShowApp
    
    preBuildScripts:
      - script: |
                if [[ -f "${PODS_ROOT}/SwiftGen/bin/swiftgen" ]]; then
                  "${PODS_ROOT}/SwiftGen/bin/swiftgen"
                else
                  echo "warning: SwiftGen is not installed. Run 'pod install --repo-update' to install it."
                fi
        name: SwiftGen

    postCompileScripts:
    - script: |
              export PATH="$PATH:/opt/homebrew/bin"
              if which swiftlint > /dev/null; then
                swiftlint
              else
                echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
              fi
      name: Swiftlint

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.giulianoaccorsi.TVShowApp
      INFOPLIST_FILE: TVShowApp/Info.plist
      CODE_SIGN_STYLE: "Manual"
      DEVELOPMENT_TEAM: ""
      PROVISIONING_PROFILE: "Wildcard"

    info:
      path: TVShowApp/Info.plist
      properties:
        UISupportedInterfaceOrientations: []
        NSAppTransportSecurity: true
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
  
  TVShowAppTests:
    platform: iOS
    type: bundle.unit-test

    sources:
      - path: TVShowAppTests
  
    dependencies:
      - target: TVShowApp

#  definicao do scheme do projeto
schemes:
  TVShowApp:
    build:
      targets:
        TVShowApp: [run, test]
      parallelizeBuild: true
      buildImplicitDependencies: true
    run:
      config: Debug
    test: 
      config: Debug
      gatherCoverageData: true
      coverageTargets: 
        - TVShowApp
      targets:
        - TVShowAppTests